### PR TITLE
feat(astro): support Astro 3.0

### PR DESCRIPTION
**Pull request by mimarec**
## Fixes
To provide support for Astro 3.0, it has been necessary to update all executors and add the utility to search for the Astro binary within node_modules.

```ts
export function getAstroBinPath(): string {
  return normalize(join(workspaceRoot, 'node_modules', '.bin', 'astro'));
}
```
This is necessary because with Astro version 3.0, the default export from the package.json file is no longer astro.js, which causes that following function is not returning the same result:

```ts
require.resolve('astro');
```
This function was responsible for returning the location of the astro.js file and passing it to the child_process responsible for executing the various executors.

package.json (version 3.0)
https://github.com/withastro/astro/blob/main/packages/astro/package.json#L35

package.json (version 2.0)
https://github.com/withastro/astro/blob/astro%402.0.4/packages/astro/package.json#L29

The new templates provided by Astro by default have been included in the application generation.

This new functionality has been tested with an NX workspace.

### CODE REVIEW

**Comment by jjtudela** [comment]
It works for me on nx 16 workspace!!

**Comment by barchero** [comment]
Tested in nx workspace and works like a charm. Thank you @mimarec

**Comment by andersonba** [comment]
Nice!! It works! Thanks.

I hope it's merged as soon as possible, the previous PR has been open for a month.

**Comment by louiss0** [comment]
> Nice!! It works! Thanks.
> 
> I hope it's merged as soon as possible, the previous PR has been open for a month.

Tell em buddy tell em. This is when view transitions are OUT!

**Comment by sarveshraj** [comment]
Could not wait to try view transitions. Moved my project targets to directly use `astro` CLI with `nx:run-commands` executor. Here's the `project.json` for impatient souls like mine:

```json
{
  "$schema": "../../node_modules/nx/schemas/project-schema.json",
  "name": "my-astro-app",
  "projectType": "application",
  "sourceRoot": "apps/my-astro-app/src",
  "tags": [],
  "targets": {
    "build": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm exec astro --root apps/my-astro-app build"
      }
    },
    "lint": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm exec astro --root apps/my-astro-app check"
      }
    },
    "serve": {
      "executor": "nx:run-commands",
      "options": {
        "command": "pnpm exec astro --root apps/my-astro-app dev"
      }
    }
  }
}
```

Replace `my-astro-app` with your app's name and `pnpm` with your preferred package manager.

**Comment by louiss0** [comment]
> Could not wait to try view transitions. Moved my project targets to directly use `astro` CLI with `nx:run-commands` executor. Here's the `project.json` for other impatient souls:
> 
> ```json
> {
>   "$schema": "../../node_modules/nx/schemas/project-schema.json",
>   "name": "my-astro-app",
>   "projectType": "application",
>   "sourceRoot": "apps/my-astro-app/src",
>   "tags": [],
>   "targets": {
>     "build": {
>       "executor": "nx:run-commands",
>       "options": {
>         "command": "pnpm exec astro --root apps/my-astro-app build"
>       }
>     },
>     "lint": {
>       "executor": "nx:run-commands",
>       "options": {
>         "command": "pnpm exec astro --root apps/my-astro-app check"
>       }
>     },
>     "serve": {
>       "executor": "nx:run-commands",
>       "options": {
>         "command": "pnpm exec astro --root apps/my-astro-app dev"
>       }
>     }
>   }
> }
> ```
> 
> Replace `my-astro-app` with your app's name and `pnpm` with your preferred package manager.

Thanks for this I can move on for now. I might just use this forever.

**Comment by Bjeaurn** [comment]
Life savers in this thread, of course it was easy enough to switch it (temporarily). Hope this gets merged soon!

**Comment by louiss0** [comment]
One last thing that needs to happen is that the `"moduleResolution"` for Astro needs to be set to "bundler" in the `tsconfig.json` file

**Comment by jesusvallez** [comment]
Any news?

**Comment by h0lybyte** [comment]
Amazing work guys! 
Can not wait to use Astro v3 in my Nx monorepo!

**Comment by louiss0** [comment]
Astro is now at version 4

**Comment by firxworx** [comment]
@louiss0 confirming: I upgraded one of my projects to Astro v4 today and everything still works great per my above instructions (https://github.com/nxtensions/nxtensions/pull/512#issuecomment-1834377721) :)

**Comment by Brian-McBride** [comment]
I was doing some work with the advanced APIs
https://docs.astro.build/en/reference/cli-reference/#advanced-apis-experimental

You could just import Astro and run build on it. 

It works with the base Astro. It seems to fail with Astro addons though. I have a feeling that the Astro plugins are assuming the directory structures is Astro (not a monorepo) or Vite needs more manual configuration. 

You can pass in a Vite config directly into the build command. So it would be possible to clean it up. 

Here is a Gist of an executor with the build command in place.
https://gist.github.com/Brian-McBride/86f43cfb4c55f778fd4c01c238d3b53c

I haven't tried it with Astro 4. Maybe things are better.

**Comment by sansaelek-ah** [comment]
Hi folks! Could you please give me a pointer on how to run the PR version instead of the NPM package? I've made a few attempts, but I can't seem to get it working. I was able to run it in the `packages/astro` directory, but not at the root level where my main Nx project is located.

Additional information: The PR version is located under `tools/` in my Nx project.

**Comment by leosvelperez** [comment]
Hey all!

I finally had a bit of time and desire to work on this. I will release a couple of major versions (aligned to the Nx version they support) that will add support for Nx v17 + Astro v3 and Nx v18 + Astro v3 & v4.

Apologies for not getting to this earlier. Big props to everyone who chimed in with some solutions and workaround. Especially to @mimarec for taking the time to put this together and @firxworx for the great tips provided 👏🏻

Moving forward, I'll try my best to find some time to maintain this better.

I'm going to close this PR in favor of https://github.com/nxtensions/nxtensions/pull/538.

**Pull request closed without merging**
